CREATE TABLE CERTIFICATES
(
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DOUBLE PRECISION
    DURATION BIGINT NOT NULL,
    CREATE_DATE TEXT NOT NULL,
    LAST_UPDATE_DATE TEXT
);
